### ISSUE TITLE
User is asking for CFDPython benchmark set-up

### ISSUE THREAD

**Issue by shriram-jagan** [nv-legate/cunumeric#1087]
This is a follow-on from the issue [here](https://github.com/nv-legate/cunumeric/issues/1080). The original issue reported by the [user](https://github.com/AngryBear2) was on perf differences between `numpy` and `cunumeric` on CPU, while this one is related to reproducing the benchmark that was run much earlier. Here's the ask from the user:

> For the test of CFDPython mentioned on the cunumeric homepage, can you provide the parameters and data of the experiment settings?

The user is interested in knowing the benchmark configurations:- problem size (per GPU?) and simulation parameters.

**Comment by manopapad** [comment]
Sorry for the delay, I was asking around regarding the original benchmark setup.

It looks like the original CFD runs used a 9k x 18k grid on 1 GPU, with the smaller dimension doubling with each doubling on the number of GPUs (i.e. on 2 GPUs the grid was 18k x 18k, then 18k x 36k on 4 GPUs etc.). The runs were done on a cluster of DGX-A100 nodes.

If you're trying to reproduce these runs, do note that Lorena Barba's original code was an ipython notebook, which the Legate team had to convert to a standalone python script (Legate can't execute notebooks multi-node at this time). The reason the standalone benchmark code hasn't been published yet is that the conversion from ipython to standalone script counts as a modification of the original code, so we need to get the Nvidia legal team involved to make sure everything is done according to license requirements.

**Comment by shriram-jagan** [comment]
@AngryBear2, I'm marking this issues as closed. Please re-open it if you need more information about the data.
