### ISSUE TITLE
np.matmul support

### ISSUE THREAD

**Issue by sionledbetter** [nv-legate/cunumeric#110]
I was specifically interested in legate because I have a program which computes many matrix multiplications and dot products of large data structures and I wanted to parallelize the numpy.matmul operations on the GPU for a performance increase.  I actually converted sparse data structures to numpy objects specifically for this, and without this support legate is useless to me.

`RuntimeWarning: cuNumeric has not implemented matmul and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.`

**Comment by manopapad** [comment]
With the merge of https://github.com/nv-legate/cunumeric/issues/110 matmul is now supported.
