### ISSUE TITLE
Cunumeric Performance Acceleration Using GPUs.

### ISSUE THREAD

**Issue by 1193749292** [nv-legate/cunumeric#1106]
Use the CFD to perform the test, the core code is as follows:
```
def cavity_flow(nt, u, v, dt, dx, dy, p, rho, nu):
    un = np.empty_like(u)
    vn = np.empty_like(v)
    b = np.zeros((ny, nx))
    
    for n in range(nt):
        un = u.copy()
        vn = v.copy()
        
        b = build_up_b(b, rho, dt, u, v, dx, dy)
        p = pressure_poisson(p, dx, dy, b)
        
        u[1:-1, 1:-1] = (un[1:-1, 1:-1]-
                         un[1:-1, 1:-1] * dt / dx *
                        (un[1:-1, 1:-1] - un[1:-1, 0:-2]) -
                         vn[1:-1, 1:-1] * dt / dy *
                        (un[1:-1, 1:-1] - un[0:-2, 1:-1]) -
                         dt / (2 * rho * dx) * (p[1:-1, 2:] - p[1:-1, 0:-2]) +
                         nu * (dt / dx**2 *
                        (un[1:-1, 2:] - 2 * un[1:-1, 1:-1] + un[1:-1, 0:-2]) +
                         dt / dy**2 *
                        (un[2:, 1:-1] - 2 * un[1:-1, 1:-1] + un[0:-2, 1:-1])))

        v[1:-1,1:-1] = (vn[1:-1, 1:-1] -
                        un[1:-1, 1:-1] * dt / dx *
                       (vn[1:-1, 1:-1] - vn[1:-1, 0:-2]) -
                        vn[1:-1, 1:-1] * dt / dy *
                       (vn[1:-1, 1:-1] - vn[0:-2, 1:-1]) -
                        dt / (2 * rho * dy) * (p[2:, 1:-1] - p[0:-2, 1:-1]) +
                        nu * (dt / dx**2 *
                       (vn[1:-1, 2:] - 2 * vn[1:-1, 1:-1] + vn[1:-1, 0:-2]) +
                        dt / dy**2 *
                       (vn[2:, 1:-1] - 2 * vn[1:-1, 1:-1] + vn[0:-2, 1:-1])))
```

Test command:  legate --gpus 4 --fbmem 30000 ./demo.py

For np.dot, the matmul operator (cunumeric/src/cunumeric/matrix/matmul.cc) is used.

However, the demo does not use any cunumeric operator (cunumeric/src/cunumeric), but uses GPU alignment for acceleration.
I want to know what makes it possible to use the power of the GPU for acceleration.

**Comment by manopapad** [comment]
I'm afraid I don't understand what your issue is exactly. Are you saying that GPUs are not being used at all? Perhaps the input size is too small, and cuNumeric is deciding it's not worth the overhead to move the data to the GPU, and instead just completes the computation entirely in Python.

**Comment by 1193749292** [comment]
@manopapad This demo uses GPUs for acceleration.
I'm just a little curious. For example, np.dot in the code is due to the call to src/cunumeric/matrix/matmul and the GPU is used for acceleration.

In the preceding demo, the (eg: CUNUMERIC_MATMUL, CUNUMERIC_DOT) operator in the cunumeric is not used, but the GPU can be used for acceleration.
I want to know how this works, maybe because the task uses a GPU and uses a TOC_PROC type processor? Is there a way to test this conjecture?

**Comment by manopapad** [comment]
> I want to know how this works

All of the arithmetic operations (multiplications, subtractions etc.) are executing on the GPU. The slices are outlining which pieces of the arrays are passed to the kernels.

> Is there a way to test this conjecture?

You can run with `--progress`, which will show which tasks are being launched, and what type of processor they're running on:

```
(a/env) iblis:~/a/cunumeric> cat c.py
import cunumeric as cn
M = cn.ones((10000,1000))
v = cn.ones((1000,))
x = M.dot(v)
(a/env) iblis:~/a/cunumeric> legate --progress --gpus 2 c.py
[0 - 7ff2a6ffc000]    0.899180 {3}{legate}: cunumeric::MatVecMulTask GPU task [c.py:4], pt = (0,0), proc = 1d00000000000007
[0 - 7ff2a6df6000]    0.899572 {3}{legate}: cunumeric::MatVecMulTask GPU task [c.py:4], pt = (1,0), proc = 1d00000000000008
[0 - 7ff2a6ffc000]    0.961869 {3}{legate}: cunumeric::UnloadCUDALibsTask GPU task [], pt = (0), proc = 1d00000000000007
[0 - 7ff2a6df6000]    0.962215 {3}{legate}: cunumeric::UnloadCUDALibsTask GPU task [], pt = (1), proc = 1d00000000000008
```

Alternatively, you can run with `--profile`/`--nsys` and visualize a trace of the execution using `legion_prof`/Nsight Systems.

**Comment by 1193749292** [comment]
Thank you very much for your answer, it works
