### ISSUE TITLE
AttributeError: type object 'ndarray' has no attribute 'convert_to_legate_array'

### ISSUE THREAD

**Issue by piyueh** [nv-legate/cunumeric#14]
Location: line 1622 in array.py
https://github.com/nv-legate/legate.numpy/blob/3452c85f93c4a886e9f4bff5f2e87b20f98b30bf/legate/numpy/array.py#L1622

I believe this is a bug. This looks like a typo to `convert_to_legate_ndarray` (the method at line 109 to 118 in the same file):
https://github.com/nv-legate/legate.numpy/blob/3452c85f93c4a886e9f4bff5f2e87b20f98b30bf/legate/numpy/array.py#L109-L118

If an example is needed to see how this is triggered, here's one:

1. step 1: create `test.py`:
   ```python
   from legate import numpy
   a = numpy.array([1, 2, 3, 0, 4, 5, 6], dtype=float)
   b = numpy.array([1, 0, 3, 0, 4, 5, 0], dtype=float)
   d = numpy.divide(a, b, out=numpy.zeros_like(b), where=(b != 0))
   print("d:", d)
   ```

2. step 2: run with, e.g., `$ legate --cpus 1 ./test.py`

The output:
```python
Traceback (most recent call last):
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 394, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "<prefix>/lib/python3.8/site-packages/legion_top.py", line 193, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./test.py", line 4, in <module>
    d = numpy.divide(a, b, out=numpy.zeros_like(b), where=(b != 0))
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/module.py", line 853, in divide
    return true_divide(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/module.py", line 1050, in true_divide
    return ndarray.perform_binary_op(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/array.py", line 2058, in perform_binary_op
    cls.get_where_thunk(
  File "<prefix>/lib/python3.8/site-packages/legate/numpy/array.py", line 1622, in get_where_thunk
    array = cls.convert_to_legate_array(where)
AttributeError: type object 'ndarray' has no attribute 'convert_to_legate_array'
```

After changing it to `convert_to_legate_ndarray`, the division works as expected.

**Comment by magnatelee** [comment]
The `where` parameter for binary operators currently doesn't work except for singleton arrays. This will be fixed by [these refactoring changes](https://github.com/magnatelee/legate.numpy/commits/type-erased-tasks) I'll merge later this month. In the meantime, please use the `where` operator.

**Comment by piyueh** [comment]
Understood. Thanks! Feel free to close the issue, or keep it open if you want to track this issue.

**Comment by magnatelee** [comment]
@piyueh Let's keep this open for now. I'll ping you on this issue once I merge the branch.

**Comment by magnatelee** [comment]
@piyueh I'm going to close this issue and create a new one to remind ourselves. (and sorry for taking it so long to add this!)
