### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by BS-astronomer** [nv-legate/cunumeric#163]
I have recently installed legate.core building from source with install.py.
Now when I try to install cuNumeric with 
./setup.py --with-core /opt/legate/
I am facing an error at the very end of compilation:
TEST 35/35 fork:safety_after_fork_in_parent [FAIL]
  ERR: Failed to fork process.

Full output from the installation is here:
[err.txt](https://github.com/nv-legate/cunumeric/files/7760356/err.txt)
[out.txt](https://github.com/nv-legate/cunumeric/files/7760357/out.txt)

**Comment by manopapad** [comment]
We've been seeing this issue more and more recently. We build OpenBLAS as part of cunumeric installation, and OpenBLAS runs its test suite on build by default, and this particular test seems to fail on certain configurations.

I just merged https://github.com/nv-legate/cunumeric/pull/158, which skips the OpenBLAS test suite on build. Please pull latest cunumeric and try again.

**Comment by BS-astronomer** [comment]
Thank you very much! Now it works!
