### ISSUE TITLE
Support partial-machine tiling

### ISSUE THREAD

**Issue by marcinz** [nv-legate/cunumeric#20]
Currently legate.numpy will either tile an array across all the nodes in the machine, or place the entire array on a single node. Both strategies may be suboptimal in certain cases, e.g. the jacobi benchmark, where the following matrix-vector multiplication happens repeatedly every timestep (`R` is a `NxN` matrix, all other variables are `Nx1` vectors):

```
x = (b - np.dot(R, x)) / d
```

The optimal partitioning for the vectors is to split them across `sqrt(N)` nodes, one for each column tile of the matrix `R`.

Besides providing the mechanism for this, someone needs to advise legate.numpy what the optimal partitioning is for each operation's output array. Doing this requires looking ahead at how this array is later used, and thus requires lazy evaluation.

**Comment by manopapad** [comment]
With #37 we have updated our heuristics on GEMV to split the output vector into `sqrt(N)` parts, which is probably the right answer most of the time. There is another heuristic, to maintain this partitioning across vector-vector operations, which is less likely to be universally correct. The right answer here is to wait to collect more operations, so we know how arrays will be used in the future, and can make informed partitioning/sharding decisions.

**Comment by manopapad** [comment]
Yes, there is a separate task for extending the partitioning to take multiple operations into account.
