### ISSUE TITLE
View partitioning ignores top-level array and other views

### ISSUE THREAD

**Issue by marcinz** [nv-legate/cunumeric#21]
Currently legate.numpy partitions the region backing an array view (slice) without considering other views or the top-level array. This can lead to tile misalignment, e.g. on the stencil benchmark, where the top-level "grid" array has one extra cell on each side compared to the "center" view. If asked to split a 37839 x 37839 grid into 4 tiles across the X dimension, legate.numpy will create the following partitions:

```
        tile 0  tile 1      tile 2       tile 3
center: 1-9460  9461-18920  18921-28380  28381-37837
grid:   0-9459  9460-18919  18920-28379  28380-37838
```

Notice that the boundaries are not aligned. This behavior has the potential to cause extra traffic, as we switch between the two partitions while working on the different arrays.

We could try to capture this case by partitioning regions for views following the top-level region partition. We would likely want to guard this optimization with a heuristic, to only apply it where it would actually be beneficial (e.g. the proposed "derived" partitioning is not horribly imbalanced, in which case we would prefer the original "equal" partitioning strategy for the view).

Note that this proposal doesn't cover the case where the partitioning of view A should be aligned with view B, but neither is related to the top-level array's partition. A lazy evaluation engine could make an informed decision even in this scenario, by waiting to tile until it has seen a number of tiled partitions that need to be made, at which point it can tile them together using something like the unification algorithm used by Regent's auto-parallelizer.

**Comment by lightsighter** [comment]
This one is mostly fixed now. Subview arrays automatically partition and shard themselves to align with how the root array is partitioned and sharded. We haven't done it for all operations yet such as `dot` but for most operations things should align.

**Comment by marcinz** [comment]
@manopapad I am guessing this is resolved?

**Comment by manopapad** [comment]
Yes, the core is handling this correctly nowadays.
