### ISSUE TITLE
Incorrect signatures for ufuncs in the API reference

### ISSUE THREAD

**Issue by magnatelee** [nv-legate/cunumeric#313]
The API reference for ufuncs currently doesn't show the right signatures:

https://nv-legate.github.io/cunumeric/22.05/api/generated/cunumeric.bitwise_and.html#cunumeric.bitwise_and

We want something like this instead:

https://numpy.org/doc/stable/reference/generated/numpy.bitwise_and.html

**Comment by bryevdv** [comment]
The sledgehammer solution would be resorting to [`autodoc-process-signature`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#event-autodoc-process-signature) but I am hoping there is a better solution

**Comment by bryevdv** [comment]
OK, I'm fairly configent it is because `autodata` is getting used for them instead of `autofunction`
```
.. autodata:: bitwise_and
[autodoc] from cunumeric import bitwise_and
[autodoc] import cunumeric => <module 'cunumeric' from '/home/bryan/work/cunumeric/cunumeric/__init__.py'>
[autodoc] getattr(_, 'bitwise_and')
[autodoc] => <function implemented.<locals>.wrapper at 0x7f9d0a0dd440>
[app] emitting event: 'autodoc-process-signature'('data', 'cunumeric.bitwise_and', <function implemented.<locals>.wrapper at 0x7f9d0a0dd440>, {}, Non
[app] emitting event: 'autodoc-process-docstring'('data', 'cunumeric.bitwise_and', <function implemented.<locals>.wrapper at 0x7f9d0a0dd440>, {}, ['C
[autodoc] output:

.. py:data:: bitwise_and
   :module: cunumeric
   :value: <function implemented.<locals>.wrapper>
```
