### ISSUE TITLE
Discussion: Bump Min Python version

### ISSUE THREAD

**Issue by bryevdv** [nv-legate/cunumeric#327]
Recently the numpy min version was bumped to 1.22 in https://github.com/nv-legate/cunumeric/pull/291. However today I discovered that Numpy 1.22 is not conda installable for Python 3.7 (https://github.com/nv-legate/cunumeric/pull/291#issuecomment-1118). (And this is because 3.8 is indeed the [min py version for Numpy 1.22](https://numpy.org/news/#numpy-1220-release))

This could be resolved by lowering the numpy min version to 1.20 (possibly with a few other changes to revert) or by bumping the min Python version to 3.8. @magnatelee stated in chat
> I’m in favor of bumping up the min python version, let's go with 3.8

I'm not sure what all changes would need to happen, and where, to truly execute a min py bump to 3.8. E.g. off the top of my head: docs/readmes, conda env files (here, in `legate.core`, on GitLab, and possibly others), updates to CI job matrices... and probably other things I haven't thought of. This issue is to hopefully get all the necessary people together to figure that out. 

cc @magnatelee @manopapad @marcinz @m3vaz 

* [x] CI images
* [x] quickstart (setup_conda.sh, make_image.sh and Dockerfile)
* [x] conda package recipes 
  - #332
  - https://github.com/nv-legate/legate.core/pull/220
* [x] conda-based Dockerfiles (WIP)
* [x] conda env files on each github repo
  - #332
  - https://github.com/nv-legate/legate.core/pull/220
* [x] READMEs on each github repo
  - #339
  -  https://github.com/nv-legate/legate.core/pull/226

**Comment by leofang** [comment]
As per [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule), which a community consensus, Python 3.7 and below should be dropped at this point. But I don't know if cuNumeric has users still on earlier Python.

**Comment by manopapad** [comment]
AFAIK this is the full list of places we need to update:

* CI images
* quickstart (setup_conda.sh, make_image.sh and Dockerfile)
* conda package recipes
* conda-based Dockerfiles (WIP)
* conda env files on each github repo
* READMEs on each github repo

I don't know if there's any dependence on the python version in the other docs.

**Comment by bryevdv** [comment]
@manopapad it looks like the default PYTHON_VER is already 3.8 everywhere in the quickstart?

**Comment by manopapad** [comment]
>  it looks like the default PYTHON_VER is already 3.8 everywhere in the quickstart? (edit: and also in legate-ci?)

Yes, you're right. I've checked off those items. And I'll also check off conda-based docker images, given that we don't have those yet :-)

**Comment by magnatelee** [comment]
#339 addresses the last bullet.
