### ISSUE TITLE
Advanced indexing operations `hang` when used on the relatively big arrays

### ISSUE THREAD

**Issue by ipdemes** [nv-legate/cunumeric#329]
Can be reproduced by:
```
A3 = np.ones(
        (
            N,
            int(N / 100),
            100,
        ),
        dtype=int,
    )
    B = np.arange(N, dtype=int)
    
    indx = B % 10
    indx3d_bool = (A3 % 2).astype(bool)
    start = datetime.datetime.now()
    for step in range(steps):
        A3[indx, :, indx] = 15
        A3[indx3d_bool] = 16
    stop = datetime.datetime.now()
```
when N>=100

**Comment by apryakhin** [comment]
Hi Irina, is this a different issue from https://github.com/StanfordLegion/legion/issues/1237?

Do we have a root cause? Just checking to see whether it's can be Realm related. Thanks!

**Comment by ipdemes** [comment]
@apryakhin yes, I believe this is a separate issue. I am trying to find the reason for the hang right now

**Comment by lightsighter** [comment]
If this is a multi-node hang, `-lg:safe_ctrlrepl 1` is always a good sanity check for a basic source of hangs.
