### ISSUE TITLE
A COPY/PASTE ERROR

### ISSUE THREAD

**Issue by hwyongshi** [nv-legate/cunumeric#331]
cunumeric/eager.py
 240     def real(self):
 241         if self.deferred is not None:
 242                return self.deferred.imag()_
 243         return EagerArray(self.runtime, self.array.real)

line 242, should the code be "_return self.deferred.real()_"

**Comment by manopapad** [comment]
Thanks for finding this! f3dbaa8e14fc38bc4056ceb070c60693ba26bfa7 fixes this error.
