### ISSUE TITLE
Failure in append test

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#362]
After the merge of https://github.com/nv-legate/cunumeric/pull/306 we are seeing a failure in the `append` testcase, e.g. see https://github.com/nv-legate/cunumeric/runs/6466837618?check_suite_focus=true. Here is a minimal example that is failing:

```
import numpy as np
import cunumeric as cn
b = np.append(np.ones((0,)), np.ones((10,)))
c = cn.append(cn.ones((0,)), cn.ones((10,)))
assert np.array_equal(b, c)
```

**Comment by sbak5** [comment]
Pushed a PR #365
