### ISSUE TITLE
`reduce_output ` seems not to free buffer memory after the first use.

### ISSUE THREAD

**Issue by ipdemes** [nv-legate/cunumeric#363]
I am using DeferredReduction<SumReduction<size_t>> to calculite size of the output array and doing it like below:

```
template <typename Output>
static __global__ void __launch_bounds__(THREADS_PER_BLOCK, MIN_CTAS_PER_SM)
my_cuda_kernel(size_t volume,
               Output out){
  size_t value=0
  for (){
    size_t val = ...
    SumReduction<size_t>::fold<true>(value, val);
  }
  printf("IRINA DEBUG before reduction val = %d\n", value);
  reduce_output(out, value);
}
size_t operator(){ 
  blocks = ...
  volume = ...
  stream = ...
  DeferredReduction<SumReduction<size_t>> size;
  my_cuda_kernel<<<blocks, THREADS_PER_BLOCK, 0, stream>>>(volume,size);
  cudaStreamSynchronize(stream);
  std::cout <<"Irina debug size  = "<<size.read()<<std::endl;
  return size.read();
}
```

This returns following output:

```
IRINA DEBUG before reduction val = 1
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 0
IRINA DEBUG before reduction val = 1
IRINA DEBUG before reduction val = 0
Irina debug size = 1544
```

So inside of the kernel it produces correct count number, but size.read() returns 1544 instead of 2 

It seems like the buffer used in `reduce_output` doesn't get freed or gets corrupted after the first use. 
To reproduce the error I needed to run following example 2 times and the wrong value was returned only on the second iteration:

```
  x = mk_seq_array(
        np,
        (
            3,
            4,
        ),
    )
    x_num = mk_seq_array(
        num,
        (
            3,
            4,
        ),
    )
    indx = np.array(
        [
            [True, False, False, False],
            [False, False, False, False],
            [False, False, False, True],
        ]
    )
    indx_num = num.array(indx)
    res = x[indx]
    res_num = x_num[indx_num]
    assert np.array_equal(res, res_num)
```

**Comment by ipdemes** [comment]
Please use this branch to debug: 
https://github.com/ipdemes/cunumeric/tree/ai_nd_output_regions
I have temporary added reproducer here https://github.com/ipdemes/cunumeric/blob/ai_nd_output_regions/tests/integration/reduction_reproducer.py

**Comment by magnatelee** [comment]
@ipdemes this is a bug in your code. `reduce_output` assumes all threads in a thread block participate the reduction (https://github.com/nv-legate/cunumeric/blob/branch-22.05/src/cunumeric/unary/scalar_unary_red.cu#L50-L51), but [some threads can terminate early in your CUDA kernel](https://github.com/ipdemes/cunumeric/blob/ai_nd_output_regions/src/cunumeric/index/advanced_indexing.cu#L73), which turns their contributions into some garbage values. Here's a minimal diff that makes the reproducer pass the test, though you'll need to make sure this is a sufficient fix:

```
diff --git a/src/cunumeric/index/advanced_indexing.cu b/src/cunumeric/index/advanced_indexing.cu
index b15b11a..52a0f63 100644
--- a/src/cunumeric/index/advanced_indexing.cu
+++ b/src/cunumeric/index/advanced_indexing.cu
@@ -40,7 +40,7 @@ static __global__ void __launch_bounds__(THREADS_PER_BLOCK, MIN_CTAS_PER_SM)
   size_t value = 0;
   for (size_t i = 0; i < iters; i++) {
     size_t idx = (i * gridDim.x + blockIdx.x) * blockDim.x + threadIdx.x;
-    if (idx > volume) return;
+    if (idx > volume) break;
     auto point = pitches.unflatten(idx, origin);
     size_t val;
     if (index[point] and ((idx + 1) % skip_size == 0)) {
```

In case you're wondering how `reduce_output` works, here's the definition: https://github.com/nv-legate/cunumeric/blob/branch-22.05/src/cunumeric/cuda_help.h#L219-L237

**Comment by ipdemes** [comment]
@magnatelee : thank you for finding this bug! I should have looked at the reduce_output implementation to understand what is wrong.
