### ISSUE TITLE
Missing task instances cause task allreduce communication to hang

### ISSUE THREAD

**Issue by mfoerste4** [nv-legate/cunumeric#374]
Under specific circumstances cunumeric/legate fails to spawn all task instances. This happened first running `test_sort.py` with 8 GPUs on prom. The following smaller code reproduces the issue most of the time (tested on prom), resulting in a hanging process during the second sort.

```
if __name__ == "__main__":
    import sys

    a = np.arange(2*3).reshape(2,3)
    print(a)
    a_num = num.array(a)

    print("Axis 0")
    sort0 = num.sort(a_num, 0)
    print(sort0)  # just for sync
    
    print("Axis 1")
    #a_num = num.array(a) # un-commenting this fixes the hang
    sort1 = num.sort(a_num, 1)   # this hangs
    print(sort1)
```
With
`LEGATE_SHOW_PROGRESS=1 LEGATE_TEST=1 test_file.py --gpus 8 -cunumeric:test --cpus 1 --omps 0`
you can see that whenever the process is hanging there are instances missing in the task. 

In gdb you can see that all task instances wait for the missing instances right in the allreduce (in fact the trace points to the subsequent memcopy).

Note that for some reason to reproduce the issue it is necessary to perform 2 operations. Also, introducing the commented line also fixes the issue. Not sure whether that is just changing the timing or the initial task somehow corrupts the array.

**Comment by magnatelee** [comment]
Should be fixed by [nv-legate/legate.core/pull/#246](https://github.com/nv-legate/legate.core/pull/246). @mfoerste4 can you pull Legate Core and again?

**Comment by mfoerste4** [comment]
> Should be fixed by [nv-legate/legate.core/pull/#246](https://github.com/nv-legate/legate.core/pull/246). @mfoerste4 can you pull Legate Core and try again?

Despite the issue with c-API of the tip (legion_logical_partition_create) the fix seems to work. I did not see any issues on prom anymore.

**Comment by magnatelee** [comment]
@mfoerste4 thanks for confirming the fix. closing the issue.
