### ISSUE TITLE
Handle overlapping sub-arrays in copies

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#40]
Currently every array copy statement is translated into a single Legion copy operation or a single task launch. If the LHS and RHS in the copy statement refer to the same array and the slices overlap, e.g. for `a[0:2] = a[1:3]`, then we will get a runtime error due to aliasing of the region requirements in the emitted operation.

This operation works fine in vanilla NumPy. To make it work in legate.numpy we would need to copy the RHS into an intermediate array, and copy from that into the LHS.

For basic copy statements it is possible we can come up with a cheap check to accurately detect overlap, and thus decide if the intermediate array is necessary (see #39). For advanced copy statements, however, this check would be much more expensive (since the set of affected indices is data-dependent), thus we should always use an intermediate array.

**Comment by ipdemes** [comment]
This use case is currently supported in cunumeric. Therefore I am closing this issue
