### ISSUE TITLE
Add custom linter to enforce sys.exit call in integration tests

### ISSUE THREAD

**Issue by bryevdv** [nv-legate/cunumeric#434]
We have to call `pytest.main` programmatically due to out reliance on `legion_python` instead of the standard Python interpreter. Because of this, integration tests *must* call `sys.exit(pytest.main(sys.argv))`, otherwise the test will *print* a failure, but not *report* a failure, i.e. that causes a CI job to fail as it should. 

We should add a linter/codebase check of some sort that enforces expected usage in tests. 

cc @marcinz

**Comment by manopapad** [comment]
@bryevdv looks like this has been fixed with #439?
