### ISSUE TITLE
Add MyPy checking to CI

### ISSUE THREAD

**Issue by bryevdv** [nv-legate/cunumeric#445]
cc @magnatelee @marcinz @trxcllnt 

I just wanted to note that using the "new install" from https://github.com/nv-legate/legate.core/pull/198 and https://github.com/nv-legate/cunumeric/pull/311 it becomes possible to run `mypy` in the completely normal, standard way. All that is required is to add an empty `py.typed` file to `legate.core` so that `mypy` will acknowledge those imports for typing purposes.

I think once the new build work is in place we should add `mypy` checking to CI. (Ideally I'd say add it to `pre-commit` but I think since it requires an installed `legate.core` that won't work on the GH pre-commit action.)

```python
env38 ❯ mypy cunumeric
cunumeric/install_info.py: note: In function "get_libpath":
cunumeric/install_info.py:15:1: error: Function is missing a return type annotation  [no-untyped-def]
    def get_libpath():
    ^
cunumeric/install_info.py: note: At top level:
cunumeric/install_info.py:23:16: error: Call to untyped function "get_libpath" in typed context  [no-untyped-call]
    libpath: str = get_libpath()
                   ^
cunumeric/runtime.py:171: error: Unused "type: ignore" comment
                    np.dtype(numpy_type), core_type  # type: ignore
                    ^
cunumeric/__init__.py:44:15: error: Call to untyped function "get_versions" in typed context  [no-untyped-call]
    __version__ = _version.get_versions()["version"]
                  ^
Found 4 errors in 3 files (checked 39 source files)
```

**Comment by marcinz** [comment]
This was done in #471.
