### ISSUE TITLE
`linalg.solve` differs from numpy

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#583]
The following code (when run with `LEGATE_TEST=1` in the environment and `-cunumeric:test`) throws `cunumeric.linalg.exception.LinAlgError: Singular matrix`:

```
import cunumeric as np

x = np.array([[5.16927712]])
assert np.linalg.det(x) != 0
y = np.linalg.solve(x, [0])
```

while no error occurs when run with numpy. Related to https://github.com/nv-legate/cunumeric/pull/568.

**Comment by rohany** [comment]
Aside from this singular value error, when it doesn't raise the error, it appears to compute incorrect values on 1x1 matrices.

**Comment by rohany** [comment]
I've figured out the problem, though I don't know the best way to solve it (I also ran into this in my own work, but thought it was an artifact of how I was casting regions to futures): future backed regions seem to not be updated by tasks! When a cunumeric ndarray / store is backed by a future, say:
```
x = store(arguments that make a future)
t = task(...)
t.add_output(x)
t.execute()
```
updates to x by t do not appear to be visible. I haven't yet made a reproducer using just legate core that shows this error, but my reasoning for believing this is the case is as follows:
* I tried printing out values in the solve routine, and the values inside `a` and `b` here https://github.com/nv-legate/cunumeric/blob/branch-22.10/src/cunumeric/matrix/solve_cpu.inl#L56 are not the same as the values when printed in the calling code, and are generally garbage.
* In the solve case, we make temporary copies of `a` and `b`, where `a` is transposed and `b` is copied because `*gesv` write into the output.
* The routine works as expected if both of these temporary stores are forced not to be backed with futures by changing the thunk creation here https://github.com/nv-legate/cunumeric/blob/branch-22.10/cunumeric/linalg/solve.py#L53 and here https://github.com/nv-legate/cunumeric/blob/branch-22.10/cunumeric/linalg/linalg.py#L661.

Annoyingly, changing all cunumeric arrays to not be backed by futures (here: https://github.com/nv-legate/cunumeric/blob/branch-22.10/cunumeric/runtime.py#L568) results in some assertion errors during `double_dispatch`.

Is this something you've seen before @magnatelee @manopapad? I imagine that it would mostly get masked by cunumeric's eager arrays etc.

**Comment by magnatelee** [comment]
first of all, if you didn't pass a store as an input as in your example, there's no guarantee that the store would contain valid values, whether it's backed by a future or a region. second, there was a bug with passing a future-back store as an inout argument, which https://github.com/nv-legate/legate.core/pull/365 should have fixed.

**Comment by rohany** [comment]
My example was incomplete -- it should have had an input. I can confirm that with the referenced PR the error goes away.
