### ISSUE TITLE
bug in `cunumeric.cumsum`

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#584]
The following program prints `[1]` instead of `[0]` when run with `LEGATE_TEST=1` in the environment and `-cunumeric:test` passed in as a command line argument:

```
import cunumeric as np
x = np.zeros((1,), dtype=np.int64)
print(np.cumsum(x))
```

**Comment by magnatelee** [comment]
should be fixed by https://github.com/nv-legate/legate.core/pull/365. @rohany can you pull and try again?

**Comment by rohany** [comment]
Yup, that fixed it.
