### ISSUE TITLE
Issue with `copy` operation for the combination of scalar and array

### ISSUE THREAD

**Issue by ipdemes** [nv-legate/cunumeric#644]
example 
```
import cunumeric as np
a= np.zeros(())
v = np.array([1,2,3,4])
a._thunk.copy(v[0]._thunk, deep=True)
print(a)
a=v[0]
print(a)
```
returns:
```
5e-324
1
```

It seems like it is a bug in the way bounds are computed for copy operation ?

**Comment by magnatelee** [comment]
@ipdemes I think this is an application bug. notice `a` and `v` have different types...

**Comment by ipdemes** [comment]
That is correct, bringing type of `v` to the same as for `a` fixes the issue
