### ISSUE TITLE
Installation hangs at src/configs/reference/lib_libreference_la-config.lo

### ISSUE THREAD

**Issue by wlai0611** [nv-legate/cunumeric#796]
When I run the ./install.py command in the cunumeric folder after having created the legate conda environment and installing legate.core, the install pauses at "Building wheel for cunumeric (pyproject.toml)"  When I turn on verbose, the step within wheel-building that seems to give it trouble is "CXX src/configs/reference/lib_libreference_la-config.lo".  Does anyone know of a work around to install cunumeric (multinode version)?

Thank you in advance!

**Comment by manopapad** [comment]
It looks like what's failing is the recursive build of [tblis](https://github.com/devinamatthews/tblis), which is used in cuNumeric to implement tensor contractions on CPUs/OpenMP. Can you try building it separately:

```
git clone https://github.com/devinamatthews/tblis.git
cd tblis
./configure --enable-thread-model=openmp --with-label-type=int32_t --with-length-type=int64_t --with-stride-type=int64_t --prefix=<tblis-install-dir>
make -j install
```

then feed the following to cuNumeric's install.py:

```
--with-tblis <tblis-install-dir>
```

**Comment by manopapad** [comment]
Currently TBLIS is unconditionally used in cuNumeric. While we consider alternatives, could you please share more information about your system (CPU architecture, OS version, compiler version etc.) and a full output of the standalone TBLIS build showing the configure & make steps, and the build error message, that we could share with the TBLIS developers?

**Comment by wlai0611** [comment]
Thanks for the quick reply, consideration and understanding.

My CPU architecture is Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
My OS version is Ubuntu 22.04
Compiler Version is gcc 11.3


The full error message is
`
Making install in src/external/tci\
make[1]: Entering directory '/home/walter/Desktop/tblis/src/external/tci'\
  CC       tci/barrier.lo\
  CC       tci/context.lo\
  CC       tci/mutex.lo\
  CC       tci/parallel.lo\
  CC       tci/slot.lo\
  CC       tci/work_item.lo\
  CC       tci/communicator.lo\
  CC       tci/task_set.lo\
  CXXLD    lib/libtci.la\
make[2]: Entering directory '/home/walter/Desktop/tblis/src/external/tci'\
 /usr/bin/mkdir -p '/home/walter/Desktop/tblis/lib'\
 /usr/bin/mkdir -p '/home/walter/Desktop/tblis/include'\
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   lib/libtci.la '/home/walter/Desktop/tblis/lib'\
 /usr/bin/mkdir -p '/home/walter/Desktop/tblis/include/tci'\
 /usr/bin/install -c -m 644  tci/tci_config.h tci/tci_global.h tci/barrier.h tci/communicator.h tci/context.h tci/mutex.h tci/parallel.h tci/pipeline.h tci/slot.h tci/task_set.h tci/work_item.h tci/yield.h '/home/walter/Desktop/tblis/include/tci'\
 /usr/bin/install -c -m 644  tci.h '/home/walter/Desktop/tblis/include/.'\
libtool: install: /usr/bin/install -c lib/.libs/libtci.so.0.0.0 /home/walter/Desktop/tblis/lib/libtci.so.0.0.0\
libtool: install: (cd /home/walter/Desktop/tblis/lib && { ln -s -f libtci.so.0.0.0 libtci.so.0 || { rm -f libtci.so.0 && ln -s libtci.so.0.0.0 libtci.so.0; }; })\
libtool: install: (cd /home/walter/Desktop/tblis/lib && { ln -s -f libtci.so.0.0.0 libtci.so || { rm -f libtci.so && ln -s libtci.so.0.0.0 libtci.so; }; })\
libtool: install: /usr/bin/install -c lib/.libs/libtci.lai /home/walter/Desktop/tblis/lib/libtci.la\
libtool: install: /usr/bin/install -c lib/.libs/libtci.a /home/walter/Desktop/tblis/lib/libtci.a\
libtool: install: chmod 644 /home/walter/Desktop/tblis/lib/libtci.a\
libtool: install: /home/walter/anaconda3/envs/legate/bin/x86_64-conda-linux-gnu-ranlib /home/walter/Desktop/tblis/lib/libtci.a\
libtool: finish: PATH="/home/walter/.local/bin:/home/walter/.cargo/bin:/usr/local/cuda-12.0/bin:/home/walter/anaconda3/envs/legate/bin:/home/walter/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/bin:/home/walter/opt/openmpi/bin:/sbin" ldconfig -n /home/walter/Desktop/tblis/lib\
----------------------------------------------------------------------\
Libraries have been installed in:\
   /home/walter/Desktop/tblis/lib\
\
If you ever happen to want to link against installed libraries\
in a given directory, LIBDIR, you must either use libtool, and\
specify the full pathname of the library, or use the '-LLIBDIR'\
flag during linking and do at least one of the following:\
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable\
     during execution\
   - add LIBDIR to the 'LD_RUN_PATH' environment variable\
     during linking\
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag\
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'\
\
See any operating system documentation about shared libraries for\
more information, such as the ld(1) and ld.so(8) manual pages.\
----------------------------------------------------------------------\
make[2]: Leaving directory '/home/walter/Desktop/tblis/src/external/tci'\
make[1]: Leaving directory '/home/walter/Desktop/tblis/src/external/tci'\
make[1]: Entering directory '/home/walter/Desktop/tblis'\
  CC       src/configs/bulldozer/lib_libbulldozer_la-bli_gemm_asm_d4x6_fma4.lo\
  CXX      src/configs/bulldozer/lib_libbulldozer_la-config_ker.lo\
  CC       src/configs/piledriver/lib_libpiledriver_la-bli_gemm_asm_d8x3.lo\
  CXX      src/configs/piledriver/lib_libpiledriver_la-config_ker.lo\
  CXX      src/configs/excavator/lib_libexcavator_la-config_ker.lo\
  CXX      src/configs/zen/lib_libzen_la-config_ker.lo\
  CC       src/configs/core2/lib_libcore2_la-bli_gemm_asm_d4x4.lo\
  CXX      src/configs/core2/lib_libcore2_la-config_ker.lo\
  CC       src/configs/sandybridge/lib_libsandybridge_la-bli_gemm_asm_d8x4.lo\
  CC       src/configs/haswell/lib_libhaswell_la-bli_gemm_asm_d6x8.lo\
  CXX      src/configs/sandybridge/lib_libsandybridge_la-config_ker.lo\
  CXX      src/configs/haswell/lib_libhaswell_la-config_ker.lo\
  CC       src/configs/knl/lib_libknl_la-bli_spackm_opt_24x16.lo\
  CC       src/configs/knl/lib_libknl_la-bli_dpackm_opt_24x8.lo\
  CC       src/configs/knl/lib_libknl_la-bli_dpackm_opt_30x8.lo\
  CC       src/configs/knl/lib_libknl_la-bli_sgemm_opt_24x16.lo\
  CC       src/configs/knl/lib_libknl_la-bli_dgemm_opt_24x8.lo\
  CXX      src/configs/knl/lib_libknl_la-config_ker.lo\
  CXX      src/configs/skx1/lib_libskx1_la-config_ker.lo\
  CC       src/configs/skx2/lib_libskx2_la-bli_sgemm_opt_12x32_l2.lo\
  CC       src/configs/skx2/lib_libskx2_la-bli_dgemm_opt_12x16_l2.lo\
  CXX      src/configs/skx2/lib_libskx2_la-config_ker.lo\
  CXX      test/1t/dot.o\
  CXX      test/test.o\
  CXX      test/1t/reduce.o\
  CXX      test/1t/scale.o\
  CXX      test/1t/replicate.o\
  CXX      test/1t/trace.o\
  CXX      test/1t/transpose.o\
  CXX      test/3m/gemm_ukr.o\
  CXX      test/3m/gemm.o\
  CXX      test/3m/gemv.o\
  CXX      test/3m/ger.o\
  CXX      test/3t/contract.o\
  CXX      test/3t/mult.o\
In file included from src/configs/bulldozer/bli_gemm_asm_d4x6_fma4.c:35:\
src/configs/bulldozer/bli_gemm_asm_d4x6_fma4.c: In function 'bli_cgemm_asm_8x4_fma4':\
src/configs/bulldozer/bli_gemm_asm_d4x6_fma4.c:1077:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 1077 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
  CXX      test/3t/outer_prod.o\
In file included from src/configs/piledriver/bli_gemm_asm_d8x3.c:38:\
src/configs/piledriver/bli_gemm_asm_d8x3.c: In function 'bli_sgemm_asm_16x3':\
src/configs/piledriver/bli_gemm_asm_d8x3.c:52:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
   52 |         void*   a_next = bli_auxinfo_next_a( data );\
      |                                              ^~~~\
./src/blis.h:18:31: note: in definition of macro 'bli_auxinfo_next_a'\
   18 | #define bli_auxinfo_next_a(x) x->a_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c:53:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
   53 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c: In function 'bli_dgemm_asm_8x3':\
src/configs/piledriver/bli_gemm_asm_d8x3.c:919:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
  919 |         void*   a_next = bli_auxinfo_next_a( data );\
      |                                              ^~~~\
./src/blis.h:18:31: note: in definition of macro 'bli_auxinfo_next_a'\
   18 | #define bli_auxinfo_next_a(x) x->a_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c:920:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
  920 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c: In function 'bli_cgemm_asm_4x2':\
src/configs/piledriver/bli_gemm_asm_d8x3.c:1634:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 1634 |         void*   a_next = bli_auxinfo_next_a( data );\
      |                                              ^~~~\
./src/blis.h:18:31: note: in definition of macro 'bli_auxinfo_next_a'\
   18 | #define bli_auxinfo_next_a(x) x->a_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c:1635:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 1635 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c: In function 'bli_zgemm_asm_2x2':\
src/configs/piledriver/bli_gemm_asm_d8x3.c:2178:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 2178 |         void*   a_next = bli_auxinfo_next_a( data );\
      |                                              ^~~~\
./src/blis.h:18:31: note: in definition of macro 'bli_auxinfo_next_a'\
   18 | #define bli_auxinfo_next_a(x) x->a_next;\
      |                               ^\
src/configs/piledriver/bli_gemm_asm_d8x3.c:2179:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 2179 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
  CXX      src/iface/1v/add.lo\
  CXX      test/3t/weight.o\
  CXX      src/iface/1v/dot.lo\
  CXX      src/iface/1v/mult.lo\
  CXX      src/iface/1v/reduce.lo\
  CXX      src/iface/1v/scale.lo\
  CXX      src/iface/1v/set.lo\
  CXX      src/iface/1v/shift.lo\
In file included from src/configs/core2/bli_gemm_asm_d4x4.c:35:\
src/configs/core2/bli_gemm_asm_d4x4.c: In function 'bli_sgemm_asm_8x4':\
src/configs/core2/bli_gemm_asm_d4x4.c:50:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
   50 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
src/configs/core2/bli_gemm_asm_d4x4.c: In function 'bli_dgemm_asm_4x4':\
src/configs/core2/bli_gemm_asm_d4x4.c:851:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
  851 |         void*   a_next = bli_auxinfo_next_a( data );\
      |                                              ^~~~\
./src/blis.h:18:31: note: in definition of macro 'bli_auxinfo_next_a'\
   18 | #define bli_auxinfo_next_a(x) x->a_next;\
      |                               ^\
src/configs/core2/bli_gemm_asm_d4x4.c:852:46: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
  852 |         void*   b_next = bli_auxinfo_next_b( data );\
      |                                              ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
  CXX      src/iface/1m/add.lo\
  CXX      src/iface/1m/dot.lo\
  CXX      src/iface/1m/reduce.lo\
  CXX      src/iface/1m/scale.lo\
In file included from src/configs/sandybridge/bli_gemm_asm_d8x4.c:38:\
src/configs/sandybridge/bli_gemm_asm_d8x4.c: In function 'bli_dgemm_asm_8x4':\
src/configs/sandybridge/bli_gemm_asm_d8x4.c:1053:42: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 1053 |     void*   b_next = bli_auxinfo_next_b( data );\
      |                                          ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
src/configs/sandybridge/bli_gemm_asm_d8x4.c: In function 'bli_cgemm_asm_8x4':\
src/configs/sandybridge/bli_gemm_asm_d8x4.c:1742:42: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]\
 1742 |     void*   b_next = bli_auxinfo_next_b( data );\
      |                                          ^~~~\
./src/blis.h:19:31: note: in definition of macro 'bli_auxinfo_next_b'\
   19 | #define bli_auxinfo_next_b(x) x->b_next;\
      |                               ^\
  CXX      src/iface/1m/set.lo\
  CXX      src/iface/1m/shift.lo\
  CXX      src/iface/1t/add.lo\
  CXX      src/iface/1t/dot.lo\
  CXX      src/iface/1t/reduce.lo\
  CXX      src/iface/1t/scale.lo\
  CXX      src/iface/1t/set.lo\
  CXX      src/iface/1t/shift.lo\
  CXX      src/iface/2m/mult.lo\
  CXX      src/iface/3m/mult.lo\
  CXX      src/iface/3t/mult.lo\
  CXX      src/internal/1v/add.lo\
  CXX      src/internal/1v/dot.lo\
  CXX      src/internal/1v/mult.lo\
  CXX      src/internal/1v/reduce.lo\
  CXX      src/internal/1v/scale.lo\
  CXX      src/internal/1v/set.lo\
  CXX      src/internal/1v/shift.lo\
  CXX      src/internal/1m/add.lo\
  CXX      src/internal/1m/dot.lo\
  CXX      src/internal/1m/reduce.lo\
  CXX      src/internal/1m/scale.lo\
  CXX      src/internal/1m/set.lo\
  CXX      src/internal/1m/shift.lo\
  CXX      src/internal/1t/dense/add.lo\
  CXX      src/internal/1t/dense/dot.lo\
  CXX      src/internal/1t/dense/reduce.lo\
  CXX      src/internal/1t/dense/scale.lo\
  CXX      src/internal/1t/dense/set.lo\
  CXX      src/internal/1t/dense/shift.lo\
  CXX      src/internal/1t/dpd/add.lo\
  CXX      src/internal/1t/dpd/dot.lo\
  CXX      src/internal/1t/dpd/reduce.lo\
  CXX      src/internal/1t/dpd/scale.lo\
  CXX      src/internal/1t/dpd/set.lo\
  CXX      src/internal/1t/dpd/shift.lo\
  CXX      src/internal/1t/indexed/add.lo\
  CXX      src/internal/1t/indexed/dot.lo\
  CXX      src/internal/1t/indexed/reduce.lo\
  CXX      src/internal/1t/indexed/scale.lo\
  CXX      src/internal/1t/indexed/set.lo\
  CXX      src/internal/1t/indexed/shift.lo\
  CXX      src/internal/1t/indexed_dpd/add.lo\
  CXX      src/internal/1t/indexed_dpd/dot.lo\
  CXX      src/internal/1t/indexed_dpd/reduce.lo\
  CXX      src/internal/1t/indexed_dpd/scale.lo\
  CXX      src/internal/1t/indexed_dpd/set.lo\
  CXX      src/internal/1t/indexed_dpd/shift.lo\
  CXX      src/internal/2m/mult.lo\
  CXX      src/internal/3m/mult.lo\
  CXX      src/internal/3t/dense/mult.lo\
  CXX      src/internal/3t/dpd/mult.lo\
  CXX      src/internal/3t/indexed/mult.lo\
  CXX      src/internal/3t/indexed_dpd/mult.lo\
  CXX      src/configs/configs.lo\
  CXX      src/util/basic_types.lo\
  CXX      src/util/configs.lo\
  CXX      src/util/cpuid.lo\
  CXX      src/util/env.lo\
  CXX      src/util/random.lo\
  CXX      src/util/thread.lo\
  CXX      src/configs/bulldozer/config.lo\
  CXX      src/configs/piledriver/config.lo\
  CXX      src/configs/excavator/config.lo\
  CXX      src/configs/zen/config.lo\
  CXX      src/configs/core2/config.lo\
  CXX      src/configs/sandybridge/config.lo\
  CXX      src/configs/haswell/config.lo\
  CXX      src/configs/knl/config.lo\
  CXX      src/configs/skx1/config.lo\
  CXX      src/configs/skx2/vpu_count.lo\
  CXX      src/configs/skx2/config.lo\
  CXX      src/configs/reference/lib_libreference_la-config.lo\
{standard input}: Assembler messages:\
{standard input}:54868: Warning: end of file not at end of a line; newline inserted\
{standard input}:56242: Error: unknown pseudo-op: `.uleb12'\
{standard input}:56220: Error: invalid operands (*UND* and .gcc_except_table._ZNK5Catch5clara8TextFlow7Columns8iteratordeB5cxx11Ev sections) for `-'\
x86_64-conda-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus\
compilation terminated.\
`

**Comment by wlai0611** [comment]
I just checked with Devin Matthews though and he said that there is not much that he can do to modify source code though.
