### ISSUE TITLE
Insufficient Memory While Trying to run "import cunumeric" with --gpus 1 flag

### ISSUE THREAD

**Issue by wlai0611** [nv-legate/cunumeric#812]
Hello,
     I hope you are well.  I have wrote a simple script called cunumeric_memory.py to import cunumeric.
````
import cunumeric as np
````
When I run the command 
````
legate cunumeric_memory.py --gpus 1
````
I receive following error:
````
[0 - 7f15ffc0d000]    0.000000 {6}{gpu}: insufficient memory on gpu 0: 4194304000 bytes needed (from -ll:fsize), 3951427584 (out of 4231069696) available
````
Would anyone know how I can successfully import cunumeric?  Why is so much memory required to import cunumeric on my GPU?

Thank you very much for any guidance you may provide.  

When I run nvidia-smi I receive this information:
````
Sun Feb 19 10:47:54 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
|  0%   43C    P8    19W / 216W |    195MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1625      G   /usr/lib/xorg/Xorg                 62MiB |
|    0   N/A  N/A      1776    C+G   ...ome-remote-desktop-daemon       70MiB |
|    0   N/A  N/A      1818      G   /usr/bin/gnome-shell               54MiB |
+-----------------------------------------------------------------------------+
````

**Comment by manopapad** [comment]
Realm (the lowest level of the cunumeric stack) registers a block of memory at startup, and allocates only out of that. The amount of memory to reserve must be specified at startup. @eddy16112 is working on an extension to query the machine resources before deciding how much to ask for, but right now the user must specify that number, and the default of 4GB is too high for your system. Try running with --fbmem 3000.

**Comment by wlai0611** [comment]
Thank you so much for the reply!  I ran the command
````
legate cunumeric_memory.py --gpus 1 --fbmem 3000
````
And it did not seem to give back the prior error.
I also receive this warning/message:
````
[0 - 7f6208b30000]    0.008748 {4}{threads}: reservation ('Python-1 proc 1d00000000000006') cannot be satisfied
````
Can this be disregarded or should I act upon this new message to use cunumeric properly?

**Comment by manopapad** [comment]
Yes, that's just a warning that Realm was unable to pin threads to cores on your system, which is not critical to have, but can result in better performance, especially for heavy CPU-only workloads.

**Comment by wlai0611** [comment]
Thank you so much for the quick and clear replies!  I am very grateful for your help.  I will close this issue.
