### ISSUE TITLE
Does cuNumeric distinguish between x86 and arm?

### ISSUE THREAD

**Issue by 1193749292** [nv-legate/cunumeric#860]
When building on aarch64
./install.py --network mpi --openmp -v --nocuda --march native
Error: No such file or directory "#include <x86intrin.h>"
![image](https://user-images.githubusercontent.com/128877897/227690354-7ef2dbd2-8c00-4b84-969e-bfa8ca662a05.png)

**Comment by 1193749292** [comment]
"#include <x86intrin.h>" appears in only two places in legion/legate.core/cunumeric

legion/runtime/legion/bitmask.h
![image](https://user-images.githubusercontent.com/128877897/227823709-1d434295-8cb7-41aa-9184-8ddc02bab3f9.png)
legion/runtime/realm/timers.inl
![image](https://user-images.githubusercontent.com/128877897/227823778-897ee790-7002-4786-b3e4-9fd6ae51febe.png)

**Comment by manopapad** [comment]
@1193749292 can you please save the entire build output to a file and share that? The partial output you included on your first comment is not coming from our software. I suspect it is coming from our recursive build of tblis.

**Comment by 1193749292** [comment]
> #796 Thank you for your answer, it's tblis. I plan to manually install tblis, comment out all "#include <x86intrin.h>" and report an error: ![image](https://user-images.githubusercontent.com/128877897/228111701-886206f6-c3d0-4014-b766-81d46bebc2f9.png)

Comment out the preceding line and change ```#include <x86intrin.h>``` to ```#include <arm_neon.h>.
#include <arm_acle.h>```
![image](https://user-images.githubusercontent.com/128877897/236400446-c37619db-a756-422f-ab16-1e8e2b62b409.png)
```
./configure --enable-thread-model=openmp --with-label-type=int32_t --with-length-type=int64_t --with-stride-type=int64_t --prefix=<tblis-install-dir>
make -j install
```
The preceding problems are solved.

**Comment by ipdemes** [comment]
@1193749292 were you able to build tblis for aarch64? I am getting some linking errors after I followed your steps.
Could you, please, provide your tblis commit hash and diff ?

**Comment by 1193749292** [comment]
@ipdemes 
![image](https://github.com/nv-legate/cunumeric/assets/128877897/e2cd9859-b715-44d5-a286-a9da134917a1)

```src/external/marray/include/``` The modification of the four programs in the path is the same. Only the header file is modified.
![image](https://github.com/nv-legate/cunumeric/assets/128877897/915ed097-5c39-475e-bbaf-ed2c19eee93f)
![image](https://github.com/nv-legate/cunumeric/assets/128877897/e22383c2-d661-43d2-871b-cf708bb9f068)
......


src/util/cpuid.cxx
![image](https://github.com/nv-legate/cunumeric/assets/128877897/e3368244-2d0e-48dc-a6ad-fc0ea1661fe1)
src/util/cpuid.hpp
![image](https://github.com/nv-legate/cunumeric/assets/128877897/50fc16c9-2599-475b-bb71-62d4d7581964)


hash:
4de1919dfe194f5e47dfc93660ce4206d8e12c4e
