### ISSUE TITLE
Isort and black conflict when formatting a file

### ISSUE THREAD

**Issue by ipdemes** [nv-legate/cunumeric#868]
It seems like `isort` and `black` conflict when formating this file : https://github.com/ipdemes/cunumeric/blob/vectorize/typings/numba/__init__.pyi 
This result in CI failure for pre-commit for the [Vectorize PR](https://github.com/nv-legate/cunumeric/pull/856)

**Comment by bryevdv** [comment]
@ipdemes `isort` does not like the vertical space, even with the comments, but `black` insists on it. I am not sure of any way to get them happy together with the comments "inline", so the simplest thing to do would just be this:
```diff
diff --git a/typings/numba/__init__.pyi b/typings/numba/__init__.pyi
index 571faf5a..3aa25ebb 100644
--- a/typings/numba/__init__.pyi
+++ b/typings/numba/__init__.pyi
@@ -1,14 +1,9 @@
 from typing import Any, Callable
 
-# Re-export types itself
 import numba.core.types as types
 import numba.cuda  # import compile_ptx
-
-# import types
 from numba.core import types
 from numba.core.ccallback import CFunc
-
-# Re-export all type names
 from numba.core.types import CPointer, uint64
 
 def cfunc(sig: Any) -> Any:
```

if you think the comments are crucial, they could go at the end of each line instead.

**Comment by ipdemes** [comment]
@bryevdv : thank you! I think we can live without this comments. Do you want to push this changes ?

**Comment by ipdemes** [comment]
I just pushed this change with other changes. Thank you.
