### ISSUE TITLE
NumPy and cuNumeric behave differently in 1 case for cunumeric.mean API

### ISSUE THREAD

**Issue by robinw0928** [nv-legate/cunumeric#870]
NumPy and cuNumeric behave differently for the following cases.
Some of the cases need to be fixed while the others are expected divergences.

Case-1
```
size = (7, 1, 1) #axis=0 fail
arr_num = num.random.randint(-5, 5, size=size)
axis = 0
out_num = num.mean(arr_num, axis=axis, keepdims=True)
```
Similar cases: 
size = (7, 1, 1) #axis=0 fail
size = (1, 7, 1) #axis=1 fail
size = (1, 1, 7) #axis=2 fail

In Numpy, it pass
In cuNumeric, it raises AssertionError as below:
 self = <cunumeric.deferred.DeferredArray object at 0x7fbfe21ddaf0>
   op = <UnaryRedCode.SUM: 10>
   src = <cunumeric.deferred.DeferredArray object at 0x7fbfe24261f0>, where = True
   orig_axis = 0, axes = (0,), keepdims = True, args = None, initial = None
   
       @auto_convert("src")
       def unary_reduction(
           self,
           op: UnaryRedCode,
           src: Any,
           where: Any,
           orig_axis: Union[int, None],
           axes: tuple[int, ...],
           keepdims: bool,
           args: Any,
           initial: Any,
       ) -> None:
           lhs_array: Union[NumPyThunk, DeferredArray] = self
           rhs_array = src
           assert lhs_array.ndim <= rhs_array.ndim
       
           argred = op in (UnaryRedCode.ARGMAX, UnaryRedCode.ARGMIN)
       
           if argred:
               argred_dtype = self.runtime.get_arg_dtype(rhs_array.dtype)
               lhs_array = self.runtime.create_empty_thunk(
                   lhs_array.shape,
                   dtype=argred_dtype,
                   inputs=[self],
               )
       
           # See if we are doing reduction to a point or another region
           if lhs_array.size == 1:
   >           assert axes is None or len(axes) == rhs_array.ndim - (
                   0 if keepdims else lhs_array.ndim
               )
   E           AssertionError
   
   cunumeric/deferred.py:3145: AssertionError

**Comment by manopapad** [comment]
Assigned you, but you should already have the privileges necessary to assign yourself. If not please let me know.

**Comment by robinw0928** [comment]
You are right. I have the privileges to assign myself.

**Comment by robinw0928** [comment]
One of the commits in PR-861 fixed this issue. It's verified and test pass. So close this issue.
