### ISSUE TITLE
Multi-node execution problem

### ISSUE THREAD

**Issue by 1193749292** [nv-legate/cunumeric#933]
```legate --launcher mpirun --nodes 3 --ranks-per-node 1 --launcher-extra ' -hostfile hostfile ' jacobi.py -b 2 -n 10 --package legate```
The test result shows that the performance is not improved. The check result shows that the command is executed once on each node instead of once. Is there a problem with the command?

**Comment by manopapad** [comment]
Can you rerun with `--verbose`, so we can see the final `mpirun` command?

The most common reason for the behavior you're seeing is that Legate was built without a networking module, so mpirun is starting multiple processes, but they all run separately and don't "collaborate" to perform a combined execution. Can you check what `legate --info` outputs?

**Comment by 1193749292** [comment]
[legate --verbose --info output.txt](https://github.com/nv-legate/cunumeric/files/11503953/legate.--verbose.--info.output.txt)

**Comment by manopapad** [comment]
Indeed it looks like your legate version was built without networking support. You will want to re-build legate with `install.py --network gasnet1` (or some other network). Notably, the conda packages don't include networking support.

I have started a PR that updates the `legate` script to detect this situation, to avoid confusion in the future: https://github.com/nv-legate/legate.core/pull/734.
